import {
  CreateDateColumn,
  DeleteDateColumn,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
  VersionColumn,
  Column,
} from 'typeorm';
import { ApiProperty } from '@nestjs/swagger';

/**
 * Abstract root entity. Every persisted entity in Jitre extends this so the
 * audit, soft-delete and optimistic-locking contract is uniform across the
 * platform.
 *
 * - `id`        — uuid v4, generated by Postgres via `uuid-ossp`.
 * - `createdAt` / `updatedAt` — managed by TypeORM.
 * - `deletedAt` — set by `softRemove` / `softDelete`. Queries auto-exclude
 *                soft-deleted rows unless `withDeleted: true` is passed.
 * - `createdBy` / `updatedBy` — uuids of users; filled by `AuditSubscriber`
 *                from RequestContext.
 * - `version`   — `@VersionColumn` for optimistic locking. Incremented on
 *                every update.
 */
export abstract class BaseEntity {
  @ApiProperty({ format: 'uuid' })
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @ApiProperty({ type: String, format: 'date-time' })
  @CreateDateColumn({ type: 'timestamptz' })
  createdAt!: Date;

  @ApiProperty({ type: String, format: 'date-time' })
  @UpdateDateColumn({ type: 'timestamptz' })
  updatedAt!: Date;

  @ApiProperty({ type: String, format: 'date-time', nullable: true })
  @DeleteDateColumn({ type: 'timestamptz', nullable: true })
  deletedAt!: Date | null;

  @ApiProperty({ type: String, format: 'uuid', nullable: true })
  @Column({ type: 'uuid', nullable: true })
  createdBy!: string | null;

  @ApiProperty({ type: String, format: 'uuid', nullable: true })
  @Column({ type: 'uuid', nullable: true })
  updatedBy!: string | null;

  @ApiProperty({ type: Number })
  @VersionColumn({ type: 'int', default: 1 })
  version!: number;
}
