import { Column, Entity, Index, Unique } from 'typeorm';
import { ApiProperty } from '@nestjs/swagger';
import { TenantEntity } from '../../common/entities/tenant.entity';
import { TaskPriority } from '@jitre/shared';

/**
 * Auto-prioritize suggestion. Generated by a daily cron that compares
 * task `dueDate`, current `priority` and recent activity. Suggestions
 * are non-mutative — users accept or dismiss them from the UI.
 */
@Entity('ai_priority_suggestions')
@Unique('ux_ai_priority_suggestions_open_task', ['taskId', 'status'])
@Index(['workspaceId', 'status'])
@Index(['taskId'])
export class AiPrioritySuggestionEntity extends TenantEntity {
  @ApiProperty({ format: 'uuid' })
  @Column({ name: 'task_id', type: 'uuid' })
  taskId!: string;

  @ApiProperty({ enum: TaskPriority })
  @Column({ name: 'current_priority', type: 'varchar' })
  currentPriority!: TaskPriority;

  @ApiProperty({ enum: TaskPriority })
  @Column({ name: 'suggested_priority', type: 'varchar' })
  suggestedPriority!: TaskPriority;

  /** Short reason shown in the UI ("due in 2 days, currently low"). */
  @ApiProperty()
  @Column({ type: 'text' })
  reason!: string;

  /** 'open' | 'accepted' | 'dismissed' | 'stale' */
  @ApiProperty({ enum: ['open', 'accepted', 'dismissed', 'stale'] })
  @Column({ type: 'text', default: 'open' })
  status!: 'open' | 'accepted' | 'dismissed' | 'stale';
}
