export enum ActivityType {
  TASK_CREATED = 'task.created',
  TASK_UPDATED = 'task.updated',
  TASK_STATUS_CHANGED = 'task.status_changed',
  TASK_ASSIGNED = 'task.assigned',
  TASK_UNASSIGNED = 'task.unassigned',
  TASK_PRIORITY_CHANGED = 'task.priority_changed',
  TASK_DUE_DATE_CHANGED = 'task.due_date_changed',
  TASK_DELETED = 'task.deleted',
  COMMENT_ADDED = 'comment.added',
  COMMENT_EDITED = 'comment.edited',
  COMMENT_DELETED = 'comment.deleted',
  ATTACHMENT_ADDED = 'attachment.added',
  ATTACHMENT_REMOVED = 'attachment.removed',
  PROJECT_CREATED = 'project.created',
  PROJECT_UPDATED = 'project.updated',
  SPRINT_STARTED = 'sprint.started',
  SPRINT_COMPLETED = 'sprint.completed',
  MEMBER_ADDED = 'member.added',
  MEMBER_REMOVED = 'member.removed',
  AI_GENERATED = 'ai.generated',
}
